#!/bin/sh
# Go through all the changed files (except for deleted and unmerged)
# Check for changed lines
added_lines="^\+"
beginning_of_line="^\+[\s]*"
evil_pattern="KAKI"
# Set exit code to 0, will be set to 1 on error.
exit_code=0
# Grep git diff of files to commit
all_files=$(
	git diff --cached --find-copies --find-renames --name-only --diff-filter=ACMRTXBU
)

if [[ -n $all_files ]]; 
then
	for file in $all_files; do
    
    kaki_comments=$(
      git diff --cached $file | grep -E "KAKI"
    )

		if [[ -n $kaki_comments ]];
		then
			echo
			echo -e "Found illegal commands in \033[1m$file:\033[0m"
			echo -e '\E[0;32m'"$lines_with_no_comment"
			echo -e "$lines_with_comment"'\033[0m'
			echo -e "$kaki_comments"'\033[0m'
			echo
			# Abort commit
			exit_code=1
		fi

	done
fi



if [ $exit_code==1 ]; then
	echo
	echo -e '\033[1m'"Commit Aborted!"'\033[0m'
	echo
fi
exit $exit_code
